# Generated by Django 2.1.7 on 2019-03-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190311_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(help_text='yyyy/mm/dd'),
        ),
    ]
