# Generated by Django 2.1.7 on 2019-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190311_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
    ]
