# Generated by Django 2.1.7 on 2019-03-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
